x-shared-env: &shared-env

services:
  database:
    image: edgedb/edgedb
    container_name: edgedb
    restart: always
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
      EDGEDB_SERVER_ADMIN_UI: enabled
      EDGEDB_SERVER_USER: edgedb
      EDGEDB_SERVER_PASSWORD: edgedb
    volumes:
      - "./database/dbschema:/dbschema"
      - "./database/data:/var/lib/edgedb/data"
    ports:
      - "5656:5656"
    networks:
      - internal

  backend:
    image: oven/bun:alpine
    container_name: backend
    working_dir: /app
    volumes:
      - "./backend:/app"
    command: sh -c "bun i && bun run dev"
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      EDGEDB_DSN: edgedb://edgedb:edgedb@edgedb:5656?tls_security=insecure
    networks:
      - internal

  frontend:
    image: node:22-alpine
    container_name: frontend
    working_dir: /app
    volumes:
      - "./frontend:/app"
    ports:
      - 5173:5173
    command: sh -c "npm i && npm run dev -- --host"
    environment:
      SERVER_URL: http://localhost:3001
    networks:
      - internal

networks:
  internal:
    driver: bridge
